version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: MegaRank
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_USER: user
      MYSQL_PASSWORD: user123

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    expose:
      - "8080"